version: '3.8'

services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro # Mount chứng chỉ SSL
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro # Mount cấu hình proxy
    depends_on:
      - wordpress
    networks:
      - wp-network

  wordpress:
    image: handmade-store-wp:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WORDPRESS_VERSION: 6.8.1 
        WOOCOMMERCE_VERSION: 9.9.5
    environment:
      - HTTP_PROTOCOL=https
      - HTTP_SERVER=localhost
      - HTTP_PORT=443
      - MYSQL_HOST=mysql
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=wp_password
      - MYSQL_DATABASE=wp_tenant_1
      - ENABLE_REMOVING_REDIRECT_CANNONICAL="true"
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=your_redis_password
    depends_on:
      - mysql
    networks:
      - wp-network

  mysql:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=wp_tenant_1
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=wp_password
    ports:
      - "3306:3306"  # Expose MySQL port to the host
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wp-network

  redis:
    image: redis:latest
    command: redis-server --requirepass your_redis_password
    ports:
      - "6379:6379"
    networks:
      - wp-network
volumes:
  mysql_data:

networks:
  wp-network:
    driver: bridge
